/* eslint @typescript-eslint/no-var-requires: "off" */
export const WhiteLogo = require('./GeotaggerAssets/GeotaggerBWLogo.png')
export const ColorLogo = require('./GeotaggerAssets/GeotaggerColorLogo.png')
export const Avatar = require('./GeotaggerAssets/Avatar.png')
export const AuthBackground = require('./GeotaggerAssets/AuthBackground.png')
export const ShowPassword = require('./GeotaggerAssets/ShowPassword.png')
export const ImagePlaceholder = require('./GeotaggerAssets/ImagePlaceholder.png')
export const Lock = require('./GeotaggerAssets/Lock.png')
export const Plus = require('./GeotaggerAssets/Plus.png')
export const MapBackground = require('./GeotaggerAssets/MapBackground.png')
export const Delete = require('./GeotaggerAssets/Delete.png')
export const Edit = require('./GeotaggerAssets/Edit.png')

export const Bled = require('./LocationsSample/Bled.png')
export const Logatec = require('./LocationsSample/logatec.png')
export const GornjiGrad = require('./LocationsSample/gornji-grad.png')